CREATE TABLE FINAN_TIPO
(idTB_TIPO CHAR(1),
DESCRICAO CHAR(15),
CONSTRAINT FINAN_TIPO_PK PRIMARY KEY(idTB_TIPO));

CREATE TABLE FINAN_CATEGORIA
(idTB_CATEGORIA CHAR(1),
DESCRICAO CHAR(15),
CONSTRAINT FINAN_CATEGORIA_PK PRIMARY KEY(idTB_CATEGORIA));

CREATE TABLE FINAN_DESPESA_RECEITA
(CODIGO NUMBER(5),
COD_TIPO CHAR(1),
COD_CATEGORIA CHAR(1),
DESCRICAO VARCHAR(70),
DIA NUMBER(2),
CONSTRAINT FINAN_DESPESA_RECEITA_PK PRIMARY KEY(CODIGO),
CONSTRAINT FINAN_TIPO_FK FOREIGN KEY(COD_TIPO) REFERENCES FINAN_TIPO,
CONSTRAINT FINAN_CATEGORIA_FK FOREIGN KEY(COD_CATEGORIA) REFERENCES FINAN_CATEGORIA);

CREATE TABLE FINAN_LANCAMENTO
(COD_D_R NUMBER(5),
MES_ANO CHAR(7),
VALOR NUMBER(9,2),
CONSTRAINT FINAN_DESPESA_RECEITA FOREIGN KEY(COD_D_R) REFERENCES FINAN_DESPESA_RECEITA,
CONSTRAINT FINAN_LANCAMENTO_PK PRIMARY KEY(MES_ANO, COD_D_R));